services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'DATABASE_URL=postgresql://postgres:tdkhoi11t@host.docker.internal:5433/gpt-portal'
      - 'DATABASE_POOL_SIZE=10'
      - 'DATABASE_POOL_MAX_OVERFLOW=20'
      - 'DATABASE_POOL_TIMEOUT=30'
      - 'DATABASE_POOL_RECYCLE=3600'
      - 'VECTOR_DB=pgvector'
      - 'PGVECTOR_DB_URL=postgresql://postgres:tdkhoi11t@host.docker.internal:5433/gpt-portal-vector'
      - 'PGVECTOR_INITIALIZE_MAX_VECTOR_LENGTH=1536'
      - 'VITE_POSTHOG_API_KEY=phc_NmZ475zYZkGW8hZYboYEAXzcLeF35fPnatNUThpFLVb'
      - 'VITE_POSTHOG_HOST=https://app.posthog.com'
      - 'STOREFRONT_URL=https://gpt-portal-publisher-storefront.sandbox.pressingly.net'
      - 'HAS_STOREFRONT=true'
      - 'STOREFRONT_SECRET=sxdl888AN8CsYhy2zxcsPQhin3BKSQ4pIdGKu0fxg8I'
      - 'STOREFRONT_TOKEN_KEY=_medusa_jwe'
      - 'LAGO_API_URL=https://gpt-portal-lagoapi.sandbox.pressingly.net/api/v1'
      - 'LAGO_API_KEY=3d8aaaa1-1ae8-4bc0-94fe-0a952adb3c18'
      - 'LAGO_TRIAL_PLAN_CODE=Starter'
      - 'STOREFRONT_EMBED_HEIGHT=600'
      - 'ENABLE_LOGIN_FORM=false'
      - 'ENABLE_OAUTH_SIGNUP=true'
      - 'OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true'
      - 'OAUTH_CLIENT_ID=6STtqtHPvAWbyWEQeIymU5Ct7uoYNpK1UzIM7Y6EAvQ'
      - 'OAUTH_CLIENT_SECRET=LP0qHXnwqYNGhpYKMh1MEaAtWPxM1_lVRpHI8IuBgJI'
      - 'OPENID_PROVIDER_URL=https://pinet-core.sandbox.pressingly.net/.well-known/openid-configuration'
      - 'OAUTH_PROVIDER_NAME=Moneta'
      - 'OAUTH_SCOPES=email profile openid moneta_id_token currency region name timezone'
      - 'OPENID_REDIRECT_URI=http://localhost:3000/oauth/oidc/callback'
      - 'DEFAULT_USER_ROLE=user'
      - 'ENABLE_FORWARD_USER_INFO_HEADERS=true'

    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
