apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gpt-portal
  name: gpt-portal-pvc
  namespace: gpt-portal
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 2Gi
