apiVersion: v1
kind: Service
metadata:
  name: gpt-portal-service
  namespace: gpt-portal
spec:
  selector:
    app: gpt-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
